version: '2'

services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123

  flaskapp:
    image: flaskpsyco
    ports:
      - "80:80"
    links:
      - postgresdb:postgres
    volumes:
      - /home/matias/distri2:/app
    restart: always
    depends_on:
      - postgresdb
    environment:
      -  -d
    expose:
      - 80
    command: -d

