version: '2'

services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - "db-data:/var/lib/postgresql/data"

  beanstalkserver:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"

  flaskapp:
    build: .
    ports:
      - "80:80"
    links:
      - postgresdb:postgres
      - beanstalkserver:beanstalk
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - postgresdb
      - beanstalkserver
    environment:
      -  -d
    expose:
      - 80
    command: -d

  beanwork:
    restart: always
    build: ./worker
    links:
      - beanstalkserver:beanstalk
    volumes:
      - ./worker:/worker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - beanstalkserver

volumes:
  db-data:
